// src/pages/BlogIndexPage.tsx
//
// 🆕 Round 28x.108 (founder: "บลอค … เผื่อจะมีเนื้อหาไหน … ไปติดคำค้นหา" ·
//   "เจาะทุกกลุ่ม") — the /blog index. Google/Meta ads are banned for this
//   vertical (CLAUDE.md §6), so organic search is the one channel that can
//   grow for free. The existing money pages all target "buy-now" queries
//   (services, districts, practitioners) which are the most contested; these
//   articles capture the earlier, less-contested "which service do I trust /
//   what are my options" intent that no competitor is writing for.
//
// Content comes from src/data/blogPosts.mjs (generated by
// scripts/buildBlogData.mjs from SEO_Blog_Pack/*.md — one source, also read by
// the crawler prerender). This page renders the card list; BlogPostPage renders
// the article. Both live inside MainLayout, so nav + footer come for free.

import React from "react";
import { Box } from "@mui/material";
import { useNavigate } from "react-router-dom";
import ArrowForwardRoundedIcon from "@mui/icons-material/ArrowForwardRounded";
import AccessTimeRoundedIcon from "@mui/icons-material/AccessTimeRounded";

import { fonts, neutrals, grays } from "@/theme";
import { responsiveShellNarrow } from "@/theme/breakpoints";
import { useDocumentMeta } from "@/utils/useDocumentMeta";
import { BLOG_POSTS } from "@/data/blogPosts";

const HERO_GRADIENT = "linear-gradient(160deg, #FF9999 0%, #FF9999 100%)";
const ORIGIN = "https://sunred.vip";

const BlogIndexPage: React.FC = () => {
  const navigate = useNavigate();

  useDocumentMeta({
    title:
      "The SunRed Journal — Outcall Massage Guides for Bangkok Travellers | SunRed",
    description:
      "Practical, no-nonsense guides to outcall massage in Bangkok — how to choose a service, late-night options, after-flight recovery, and travel-specific advice. Written for international visitors by SunRed.",
    url: `${ORIGIN}/blog`,
    type: "website",
    jsonLd: {
      "@context": "https://schema.org",
      "@type": "Blog",
      "@id": `${ORIGIN}/blog#blog`,
      name: "The SunRed Journal",
      url: `${ORIGIN}/blog`,
      description:
        "Guides to outcall massage in Bangkok for international travellers.",
      publisher: { "@id": `${ORIGIN}/#business` },
      blogPost: BLOG_POSTS.map((p) => ({
        "@type": "BlogPosting",
        headline: p.title,
        url: p.url,
        description: p.metaDescription,
      })),
    },
  });

  return (
    <Box
      sx={{
        ...responsiveShellNarrow,
        background: neutrals.n50,
        borderRadius: { xs: "28px", md: 0 },
        overflow: "hidden",
        position: "relative",
        boxShadow: { xs: "0 16px 40px rgba(45, 45, 43, 0.06)", md: "none" },
        padding: { xs: "32px 20px 48px", md: "56px 32px 80px" },
      }}
    >
      {/* ── header band ─────────────────────────────────────────────── */}
      <Box
        sx={{
          background: HERO_GRADIENT,
          mx: { xs: "-20px", md: "0px" },
          mt: { xs: "-32px", md: "-56px" },
          mb: { xs: 4, md: 6 },
          px: { xs: "24px", md: "44px" },
          pt: { xs: "48px", md: "72px" },
          pb: { xs: "34px", md: "48px" },
          textAlign: { xs: "left", md: "center" },
        }}
      >
        <Box
          sx={{
            fontFamily: fonts.body,
            fontSize: 11,
            fontWeight: 700,
            letterSpacing: "0.20em",
            textTransform: "uppercase",
            color: "rgba(255,255,255,0.72)",
          }}
        >
          SunRed · Bangkok
        </Box>
        <Box
          component="h1"
          sx={{
            fontFamily: fonts.heading,
            fontSize: { xs: 30, md: 44 },
            fontWeight: 500,
            lineHeight: 1.12,
            letterSpacing: "-0.01em",
            color: "#fff",
            margin: "12px 0 0",
          }}
        >
          The SunRed Journal
        </Box>
        <Box
          sx={{
            fontFamily: fonts.body,
            fontSize: { xs: 14, md: 16 },
            lineHeight: 1.6,
            color: "rgba(255,255,255,0.86)",
            margin: { xs: "10px 0 0", md: "14px auto 0" },
            maxWidth: 560,
          }}
        >
          Straight, useful guides to outcall massage in Bangkok — for travellers
          who’d rather book right the first time.
        </Box>
      </Box>

      {/* ── article cards ───────────────────────────────────────────── */}
      <Box sx={{ display: "flex", flexDirection: "column", gap: { xs: 2, md: 2.5 } }}>
        {BLOG_POSTS.map((p) => (
          <Box
            key={p.slug}
            component="article"
            onClick={() => navigate(`/blog/${p.slug}`)}
            sx={{
              cursor: "pointer",
              background: "#fff",
              border: `1px solid ${neutrals.n200}`,
              borderRadius: "18px",
              padding: { xs: "18px 18px", md: "24px 26px" },
              transition: "transform .18s ease, box-shadow .18s ease, border-color .18s ease",
              "&:hover": {
                transform: "translateY(-2px)",
                boxShadow: "0 12px 30px rgba(45,45,43,0.09)",
                borderColor: "#D97C9566",
              },
            }}
          >
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                gap: 1,
                fontFamily: fonts.body,
                fontSize: 11.5,
                fontWeight: 600,
                letterSpacing: "0.06em",
                textTransform: "uppercase",
                color: "#FF9999",
              }}
            >
              <AccessTimeRoundedIcon sx={{ fontSize: 14 }} />
              {p.readingMinutes} min read
            </Box>
            <Box
              component="h2"
              sx={{
                fontFamily: fonts.heading,
                fontSize: { xs: 20, md: 24 },
                fontWeight: 500,
                lineHeight: 1.22,
                letterSpacing: "-0.01em",
                color: grays.g900,
                margin: "8px 0 0",
              }}
            >
              {p.title}
            </Box>
            <Box
              sx={{
                fontFamily: fonts.body,
                fontSize: { xs: 14, md: 15 },
                lineHeight: 1.6,
                color: grays.g600,
                margin: "8px 0 0",
                display: "-webkit-box",
                WebkitLineClamp: 2,
                WebkitBoxOrient: "vertical",
                overflow: "hidden",
              }}
            >
              {p.excerpt}
            </Box>
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                gap: 0.5,
                fontFamily: fonts.body,
                fontSize: 13.5,
                fontWeight: 600,
                color: "#FF9999",
                margin: "14px 0 0",
              }}
            >
              Read the guide
              <ArrowForwardRoundedIcon sx={{ fontSize: 16 }} />
            </Box>
          </Box>
        ))}
      </Box>

      {/* ── closing line back to the product ────────────────────────── */}
      <Box
        sx={{
          fontFamily: fonts.body,
          fontSize: 13.5,
          lineHeight: 1.6,
          color: grays.g500,
          textAlign: "center",
          margin: { xs: "28px 0 0", md: "40px 0 0" },
        }}
      >
        Ready to book?{" "}
        <Box
          component="span"
          onClick={() => navigate("/")}
          sx={{ color: "#FF9999", fontWeight: 600, cursor: "pointer" }}
        >
          See tonight’s live availability →
        </Box>
      </Box>
    </Box>
  );
};

export default BlogIndexPage;
